_target_: policy_model.GemmaAgent
config:
  model_name_or_path: "/scratch/gpfs/cd2853/models/gemma-2-2b"
  generation_args:
    temperature: 0.0
    max_new_tokens: 512
    repetition_penalty: 1.0
    do_sample: False
    no_repeat_ngram_size: 0
  inference_mode: "rmr"
  few_shot_path: /home/cd2853/rational_metareasoning/data/few_shot_prompts.json