_target_: trainers.sft_trainer.SFTTrainer
# @package _global_
defaults:
- /model: phi
args: 
  _target_: trainers.sft_trainer.SFTTrainingArguments
  batch_size: 16
  learning_rate: 1e-6
  log_with: wandb
  output_dir: /scratch/gpfs/cd2853/models/
  output_suffix: "_sft"
  logging_steps: 4
  eval_steps: 16
  save_steps: 16
  warmup_ratio: 0.01
  max_grad_norm: 0.5
train_dataset_path: /home/cd2853/rational_metareasoning/data/filtered/train_all.json
eval_dataset_path: /home/cd2853/rational_metareasoning/data/filtered/val_all.json
test_dataset_path: /home/cd2853/rational_metareasoning/data/filtered/test_all.json
type: cot
