_target_: trainers.mr_trainer.MRTrainer
# @package _global_
defaults:
- /model: phi
args: 
  _target_: trainers.rl_trainer.TrainingArguments
  batch_size: 512
  mini_batch_size: 16
  learning_rate: 1e-6
  start_step: 0
  output_dir: insert_output_dir
  output_suffix: "_mr"
  rollout_sample_size: 3
  voc_gamma: 1e-1 
  logging_steps: 1
  eval_steps: 1
  save_steps: 1
  warmup_ratio: 0.01
  max_grad_norm: 1.0
train_dataset_path: insert_path_to_train_dataset
eval_dataset_path: insert_path_to_eval_dataset
test_dataset_path: insert_path_to_test_dataset
type: mr
force_direct: false
