_target_: trainers.star_trainer.StarTrainer
# @package _global_
defaults:
- /model: phi2
args: 
  _target_: trainers.ei_trainer.EITrainingArguments
  batch_size: 512
  mini_batch_size: 16
  learning_rate: 1e-6
  start_step: 0
  output_dir: /mnt/u14157_ic_nlp_001_files_nfs/nlpdata1/home/desabbat/projects/Rational_Metareasoning/models/
  data_dir: /mnt/u14157_ic_nlp_001_files_nfs/nlpdata1/home/desabbat/projects/Rational_Metareasoning/data/training_data/
  output_suffix: "_star"
  logging_steps: 1
  eval_steps: 1
  save_steps: 1
  warmup_ratio: 0.01
  max_grad_norm: 1.0
  use_hint: true
  gradient_checkpointing: true
train_dataset_path: /mnt/u14157_ic_nlp_001_files_nfs/nlpdata1/home/desabbat/projects/Rational_Metareasoning/data/filtered/train_all.json
eval_dataset_path: /mnt/u14157_ic_nlp_001_files_nfs/nlpdata1/home/desabbat/projects/Rational_Metareasoning/data/filtered/val_all.json
test_dataset_path: /mnt/u14157_ic_nlp_001_files_nfs/nlpdata1/home/desabbat/projects/Rational_Metareasoning/data/filtered/test_all.json
type: star
